name: Bump version of Tablehub component, update changelog, open pull request

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@devtronaut'
      - name: Install dependencies
        run: npm ci
      - name: Setup git
        run: |
          git config user.name "devtronaut"
          git config user.email "devtronaut@hotmail.com"
      - name: Update version
        id: update_version
        run: |
          echo "version=$(npm version ${{ github.event.inputs.version }} --no-git-tag-version)" >> $GITHUB_OUTPUT
      - name: Update changelog
        id: update_changelog
        run: |
          sed -i 's/Unreleased/${{ steps.update_version.outputs.version }}/g'   CHANGELOG.md
      - name: Create PR
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.update_version.outputs.version }}
          title: 'Release: ${{ steps.update_version.outputs.version }} Pull Request'
          body: "This pull request contains the updated package.json with the new release version"
          base: main   
